version: "3.7"

services:

    import-stories-feedly:
        image: dockermediacloud/import-stories-feedly:latest
        stop_signal: SIGKILL
        volumes:
            - type: bind
              source: ./bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./src/
              target: /opt/mediacloud/src/import-stories-feedly/
            - type: bind
              source: ./../import-stories-base/src/
              target: /opt/mediacloud/src/import-stories-base/
            - type: bind
              source: ./../extract-and-vector/src/
              target: /opt/mediacloud/src/extract-and-vector/
            - type: bind
              source: ./../common/src/
              target: /opt/mediacloud/src/common/
        depends_on:
            - postgresql-pgbouncer

    postgresql-pgbouncer:
        image: dockermediacloud/postgresql-pgbouncer:latest
        stop_signal: SIGKILL
        expose:
            - 6432
        depends_on:
            - postgresql-server

    postgresql-server:
        image: dockermediacloud/postgresql-server:latest
        stop_signal: SIGKILL
        expose:
            - 5432
