version: "3.7"

services:

    topics-mine:
        image: dockermediacloud/topics-mine:latest
        stop_signal: SIGKILL
        environment:
            MC_CRIMSON_HEXAGON_API_KEY: "${MC_CRIMSON_HEXAGON_API_KEY}"
            MC_TWITTER_CONSUMER_KEY: "${MC_TWITTER_CONSUMER_KEY}"
            MC_TWITTER_CONSUMER_SECRET: "${MC_TWITTER_CONSUMER_SECRET}"
            MC_TWITTER_ACCESS_TOKEN: "${MC_TWITTER_ACCESS_TOKEN}"
            MC_TWITTER_ACCESS_TOKEN_SECRET: "${MC_TWITTER_ACCESS_TOKEN_SECRET}"
        expose:
            # test_tm_mine.t's test HTTP servers:
            - 8890
            - 8891
            - 8892
            - 8893
            - 8894
            - 8895
        volumes:
            - type: bind
              source: ./bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./src/
              target: /opt/mediacloud/src/topics-mine/
            - type: bind
              source: ./tests/
              target: /opt/mediacloud/tests/
            - type: bind
              source: ./../topics-base/src/
              target: /opt/mediacloud/src/topics-base/
            - type: bind
              source: ./../common/src/
              target: /opt/mediacloud/src/common/
        depends_on:
            - postgresql-pgbouncer
            - rabbitmq-server
            - topics-fetch-link
            - topics-extract-story-links
            # 1) test_topics_mine.t calls topics-fetch-link
            # 2) topics-fetch-link calls _try_fetch_topic_url()
            # 3) _try_fetch_topic_url() calls generate_story()
            # 4) generate_story() calls _extract_story()
            # 5) _extract_story() runs a remote extraction job
            - extract-and-vector

    extract-and-vector:
        image: dockermediacloud/extract-and-vector:latest
        stop_signal: SIGKILL
        depends_on:
            - postgresql-pgbouncer
            - extract-article-from-page

    extract-article-from-page:
        image: dockermediacloud/extract-article-from-page:latest
        stop_signal: SIGKILL
        expose:
            - 8080

    postgresql-pgbouncer:
        image: dockermediacloud/postgresql-pgbouncer:latest
        stop_signal: SIGKILL
        expose:
            - 6432
        depends_on:
            - postgresql-server

    postgresql-server:
        image: dockermediacloud/postgresql-server:latest
        stop_signal: SIGKILL
        expose:
            - 5432

    rabbitmq-server:
        image: dockermediacloud/rabbitmq-server:latest
        stop_signal: SIGKILL
        expose:
            - 5672
            - 15672

    topics-fetch-link:
        image: dockermediacloud/topics-fetch-link:latest
        stop_signal: SIGKILL

    topics-extract-story-links:
        image: dockermediacloud/topics-extract-story-links:latest
        stop_signal: SIGKILL
