version: "3.7"

services:

    nytlabels-update-story-tags:
        image: dockermediacloud/nytlabels-update-story-tags:latest
        stop_signal: SIGKILL
        environment:
            MC_NYTLABELS_VERSION_TAG: "nyt_labeller_v1.0.0"
            MC_NYTLABELS_TAG_SET: "nyt_labels"
        volumes:
            - type: bind
              source: ./bin/
              target: /opt/mediacloud/bin/
            - type: bind
              source: ./src/
              target: /opt/mediacloud/src/nytlabels-update-story-tags/
            - type: bind
              source: ./tests/
              target: /opt/mediacloud/tests/
            - type: bind
              source: ./../nytlabels-base/src/
              target: /opt/mediacloud/src/nytlabels-base/
            - type: bind
              source: ./../common/src/
              target: /opt/mediacloud/src/common/
        depends_on:
            - postgresql-pgbouncer

    postgresql-pgbouncer:
        image: dockermediacloud/postgresql-pgbouncer:latest
        stop_signal: SIGKILL
        expose:
            - 6432
        depends_on:
            - postgresql-server

    postgresql-server:
        image: dockermediacloud/postgresql-server:latest
        stop_signal: SIGKILL
        expose:
            - 5432
